---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd   # important
spec:
  project: default
  source:
    repoURL: https://github.com/dderichswei/argocd.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://192.168.25.128:8443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false