apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:

  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
      
        resources:
           limits:
             memory: 600Mi
             cpu: 1
           requests:
             memory: 300Mi
             cpu: 500m
        name: nginx
        ports:
        - containerPort: 80
