apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  limits:
  - max:
    cpu: "800m"
  min:
    cpu: "200m"
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
